---
- include_tasks: setup-repo-Debian.yml
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution != 'Ubuntu'

- include_tasks: setup-repo-Ubuntu.yml
  when:
    - ansible_distribution == 'Ubuntu'

- name: "Refresh apt sources list"
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: "Install Skype"
  apt:
    name: "{{ skype_package }}"
    state: present
