---
- name: "Ensure HTTPS apt transport installed."
  apt:
    name: "apt-transport-https"
    state: present

- name: "Add repository."
  template:
    src: templates/skype-stable.list.j2
    dest: /etc/apt/sources.list.d/skype-stable.list

- name: "Add repo key."
  apt_key:
    url: "{{ skype_gpg_key_url }}"
